---
title: "messing around"
author: "Ziling"
format:
  pdf: default
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(stringr)
library(rvest)
library(polite)
library(sf)
library(maps)
library(viridis)
library(leaflet)
library(htmltools)
library(janitor)
library(httr2)
library(httr)
library(lubridate)
library(tidycensus)
library(purrr)
```

```{r}
```

```{r}
crop_prices2 <- crop_prices |>
  left_join(seed_deets |>
  select(-1)) |>
  select(-1) |>
  mutate(profession = replace_na(profession, "none"),
         sub_category = replace_na(sub_category, "Special Crop"),
         growth_time = replace_na(growth_time, 0),
         general_store = replace_na(general_store, 0),
         jojamart = replace_na(jojamart, 0),
         oasis_price = replace_na(oasis_price, 0)) |>
  filter(!item %in% c("Qi_Fruit", "Tea_Leaves"))

write.csv(crop_prices2, "data/crop_prices2.csv")
```

```{r}
fish_prices |>
  filter(item == "Albacore" & profession == "fisher") |>
  mutate(albaprice = regular_price * 2,
         total = albaprice) |>
  select(item, albaprice, total)
```

```{r}
tablemaybe <- function(fish, prof, amount, grade) {
  input = str_c("grade", "_price")
  fish_prices |>
    filter(item == fish & profession == profession) |>
    mutate(profit = input * 4)
}

tablemaybe("Albacore", "fisher", 4, "regular")

grade = str_c("regular", "_price")
```

```{r}
tablemaybe <- function(fish, prof, amount, grade) {
  input <- str_c(grade, "_price") # Create the column name as a string
  fish_prices |>
    filter(item == fish & profession == prof) |>
    mutate(profit = !!sym(input) * amount) |>
    select(item, profession, profit)
}

# Example call
tablemaybe("Albacore", "fisher", 4, "regular")
```

```{r}
tablemaybe2 <- function(fish, prof, amounts, grade) {
  input <- str_c(grade, "_price") # Dynamically create the column name
  fish_prices |>
    filter(item %in% fish & profession == prof) |> # Allow multiple fish selection
    mutate(profit = across(all_of(input)) * amounts) |> # Calculate profit for each selection
    summarise(total_profit = sum(profit, na.rm = TRUE)) # Summarize total profit
}

# Example data
fish_pricestest <- tibble(
  item = c("Albacore", "Salmon", "Tuna"),
  profession = c("fisher", "fisher", "angler"),
  regular_price = c(5, 10, 7),
  premium_price = c(8, 15, 12)
)

# Example call
fish_selection <- c("Albacore", "Salmon")
amounts <- c(4, 6) # Amounts corresponding to selected fish
tablemaybe2(fish_selection, "fisher", amounts, "regular")
```

```{r}

```


